"""Seed data for Opportune — sample opportunities from real-world platforms."""
from datetime import datetime, timezone, timedelta
import uuid


def _date(days_from_now: int) -> str:
    return (datetime.now(timezone.utc) + timedelta(days=days_from_now)).isoformat()


SEED_OPPORTUNITIES = [
    {
        "id": str(uuid.uuid4()),
        "title": "MLH Global Hack Week: AI/ML",
        "organization": "Major League Hacking",
        "type": "hackathon",
        "field": "Computer Science",
        "description": "A week-long virtual hackathon focused on AI/ML projects. Build, learn, and ship with thousands of student developers worldwide. Workshops daily.",
        "country": "Global",
        "remote": True,
        "grade_levels": ["high_school", "undergrad", "grad"],
        "eligibility": "Open to all students. No prior experience required.",
        "deadline": _date(21),
        "prize": "$5,000 in prizes + swag",
        "url": "https://mlh.io/",
        "source": "MLH",
        "tags": ["AI", "ML", "Hackathon", "Beginner Friendly"],
        "featured": True,
        "popularity": 982,
    },
    {
        "id": str(uuid.uuid4()),
        "title": "Pioneer Research Program",
        "organization": "Pioneer Academics",
        "type": "research",
        "field": "Multidisciplinary",
        "description": "Selective online research program where high schoolers work 1-on-1 with university professors on an original research project for college credit.",
        "country": "USA",
        "remote": True,
        "grade_levels": ["high_school"],
        "eligibility": "High school students with strong academic record (3.5 GPA+).",
        "deadline": _date(35),
        "prize": "Full transferable college credit",
        "url": "https://pioneeracademics.com",
        "source": "Pioneer Academics",
        "tags": ["Research", "College Credit", "Selective"],
        "featured": True,
        "popularity": 1240,
    },
    {
        "id": str(uuid.uuid4()),
        "title": "Lumiere Research Scholar Program",
        "organization": "Lumiere Education",
        "type": "research",
        "field": "Multidisciplinary",
        "description": "12-week independent research program with PhD mentors from Harvard, Stanford, Yale, Oxford. Produce a publishable research paper.",
        "country": "Global",
        "remote": True,
        "grade_levels": ["high_school"],
        "eligibility": "High schoolers grade 9-12. Application + transcript.",
        "deadline": _date(18),
        "prize": "Research paper + mentor recommendation",
        "url": "https://www.lumiere-education.com/",
        "source": "Lumiere",
        "tags": ["Research", "Ivy League Mentors"],
        "featured": True,
        "popularity": 1567,
    },
    {
        "id": str(uuid.uuid4()),
        "title": "Coca-Cola Scholars Program",
        "organization": "Coca-Cola Foundation",
        "type": "scholarship",
        "field": "Multidisciplinary",
        "description": "$20,000 scholarship for graduating high school seniors with leadership, academic, and service excellence. 150 recipients each year.",
        "country": "USA",
        "remote": False,
        "grade_levels": ["high_school"],
        "eligibility": "U.S. high school senior, 3.0 GPA+, planning to pursue degree.",
        "deadline": _date(45),
        "prize": "$20,000 scholarship",
        "url": "https://www.scholarships.com",
        "source": "Scholarships.com",
        "tags": ["Scholarship", "Leadership", "$20K"],
        "featured": True,
        "popularity": 2103,
    },
    {
        "id": str(uuid.uuid4()),
        "title": "Google Summer of Code 2026",
        "organization": "Google",
        "type": "internship",
        "field": "Computer Science",
        "description": "Global, online program focused on bringing new contributors into open source software development. Stipend + mentorship for 12 weeks.",
        "country": "Global",
        "remote": True,
        "grade_levels": ["undergrad", "grad"],
        "eligibility": "18+ years old, eligible to work in country of residence.",
        "deadline": _date(60),
        "prize": "$3,000–$6,600 stipend",
        "url": "https://www.linkedin.com/home",
        "source": "LinkedIn",
        "tags": ["Open Source", "Internship", "Paid"],
        "featured": False,
        "popularity": 1899,
    },
    {
        "id": str(uuid.uuid4()),
        "title": "International Mathematical Olympiad",
        "organization": "IMO Foundation",
        "type": "olympiad",
        "field": "Mathematics",
        "description": "World championship mathematics competition for high school students. Six problems over two days. Country teams of up to six.",
        "country": "Global",
        "remote": False,
        "grade_levels": ["high_school"],
        "eligibility": "Under 20, not enrolled in tertiary education. Country selection required.",
        "deadline": _date(90),
        "prize": "Gold/Silver/Bronze medals",
        "url": "https://www.imo-official.org/",
        "source": "IMO",
        "tags": ["Olympiad", "Math", "Prestigious"],
        "featured": True,
        "popularity": 1455,
    },
    {
        "id": str(uuid.uuid4()),
        "title": "Devpost: ETHGlobal Hackathon",
        "organization": "ETHGlobal",
        "type": "hackathon",
        "field": "Blockchain",
        "description": "Build the future of Web3 in 48 hours. $500K+ in prizes, mentorship from leading protocols.",
        "country": "Global",
        "remote": True,
        "grade_levels": ["undergrad", "grad", "professional"],
        "eligibility": "Anyone 18+. Teams of up to 5.",
        "deadline": _date(14),
        "prize": "$500,000+ prize pool",
        "url": "https://devpost.com/hackathons",
        "source": "Devpost",
        "tags": ["Hackathon", "Web3", "Crypto"],
        "featured": False,
        "popularity": 877,
    },
    {
        "id": str(uuid.uuid4()),
        "title": "Internshala Summer Internship",
        "organization": "Internshala",
        "type": "internship",
        "field": "Multidisciplinary",
        "description": "India's largest internship platform — find paid remote and in-office internships across product, marketing, design, and engineering.",
        "country": "India",
        "remote": True,
        "grade_levels": ["undergrad", "grad"],
        "eligibility": "College students of any year.",
        "deadline": _date(30),
        "prize": "Paid stipend ₹10K–₹40K/month",
        "url": "https://internshala.com/",
        "source": "Internshala",
        "tags": ["Internship", "India", "Paid"],
        "featured": False,
        "popularity": 2200,
    },
    {
        "id": str(uuid.uuid4()),
        "title": "Regeneron Science Talent Search",
        "organization": "Society for Science",
        "type": "competition",
        "field": "STEM",
        "description": "America's oldest and most prestigious science research competition for high school seniors. $3.1M in awards.",
        "country": "USA",
        "remote": False,
        "grade_levels": ["high_school"],
        "eligibility": "U.S. high school seniors with original research project.",
        "deadline": _date(50),
        "prize": "Up to $250,000",
        "url": "https://www.societyforscience.org/regeneron-sts/",
        "source": "Society for Science",
        "tags": ["Research", "Science", "$250K"],
        "featured": True,
        "popularity": 1320,
    },
    {
        "id": str(uuid.uuid4()),
        "title": "Rhodes Scholarship",
        "organization": "Rhodes Trust",
        "type": "scholarship",
        "field": "Multidisciplinary",
        "description": "Fully-funded postgraduate study at the University of Oxford. The oldest international scholarship program in the world.",
        "country": "UK",
        "remote": False,
        "grade_levels": ["undergrad", "grad"],
        "eligibility": "Age 18–24, undergraduate degree by July, citizen of constituency.",
        "deadline": _date(75),
        "prize": "Full Oxford tuition + stipend",
        "url": "https://www.rhodeshouse.ox.ac.uk/",
        "source": "BigFuture",
        "tags": ["Scholarship", "Oxford", "Prestigious"],
        "featured": True,
        "popularity": 1788,
    },
    {
        "id": str(uuid.uuid4()),
        "title": "Hack Club Assemble",
        "organization": "Hack Club",
        "type": "hackathon",
        "field": "Computer Science",
        "description": "In-person hackathon for teen hackers in San Francisco. Travel stipends available for international students.",
        "country": "USA",
        "remote": False,
        "grade_levels": ["high_school"],
        "eligibility": "Under 18, attending high school.",
        "deadline": _date(22),
        "prize": "Travel grants + prizes",
        "url": "https://mlh.io/",
        "source": "MLH",
        "tags": ["Hackathon", "Teens", "In-Person"],
        "featured": False,
        "popularity": 654,
    },
    {
        "id": str(uuid.uuid4()),
        "title": "Gates Cambridge Scholarship",
        "organization": "Bill & Melinda Gates Foundation",
        "type": "scholarship",
        "field": "Multidisciplinary",
        "description": "Full-cost postgraduate scholarship at the University of Cambridge for outstanding applicants from outside the UK.",
        "country": "UK",
        "remote": False,
        "grade_levels": ["undergrad", "grad"],
        "eligibility": "Non-UK citizen applying for full-time PG at Cambridge.",
        "deadline": _date(40),
        "prize": "Full tuition + stipend",
        "url": "https://www.gatescambridge.org/",
        "source": "BigFuture",
        "tags": ["Scholarship", "Cambridge", "Full-Ride"],
        "featured": False,
        "popularity": 988,
    },
    {
        "id": str(uuid.uuid4()),
        "title": "Microsoft Student Ambassadors",
        "organization": "Microsoft",
        "type": "leadership",
        "field": "Technology",
        "description": "Join a global community of student leaders. Build technical and leadership skills with Microsoft mentors. Free Azure credits.",
        "country": "Global",
        "remote": True,
        "grade_levels": ["undergrad", "grad"],
        "eligibility": "Currently enrolled in an accredited academic institution, 16+.",
        "deadline": _date(28),
        "prize": "Azure credits + swag + certification",
        "url": "https://studentambassadors.microsoft.com/",
        "source": "LinkedIn",
        "tags": ["Leadership", "Tech", "Community"],
        "featured": False,
        "popularity": 1102,
    },
    {
        "id": str(uuid.uuid4()),
        "title": "USA Computing Olympiad (USACO)",
        "organization": "USACO",
        "type": "olympiad",
        "field": "Computer Science",
        "description": "Competitive programming olympiad with 4 yearly contests. Top finishers represent USA at IOI.",
        "country": "USA",
        "remote": True,
        "grade_levels": ["high_school"],
        "eligibility": "Pre-college students. Open to international participants (Bronze→Platinum).",
        "deadline": _date(10),
        "prize": "Camp invite + IOI selection",
        "url": "http://www.usaco.org/",
        "source": "USACO",
        "tags": ["Olympiad", "Coding", "Competitive"],
        "featured": True,
        "popularity": 1444,
    },
    {
        "id": str(uuid.uuid4()),
        "title": "YouthHack Build the Future",
        "organization": "YouthHack",
        "type": "competition",
        "field": "Entrepreneurship",
        "description": "Global startup pitch competition for student entrepreneurs. Mentorship from VCs and seed funding for top teams.",
        "country": "Global",
        "remote": True,
        "grade_levels": ["high_school", "undergrad"],
        "eligibility": "Students 16–25 with a startup idea.",
        "deadline": _date(38),
        "prize": "$10,000 seed grant",
        "url": "https://devpost.com/hackathons",
        "source": "Devpost",
        "tags": ["Startup", "Pitch", "Funding"],
        "featured": False,
        "popularity": 612,
    },
    {
        "id": str(uuid.uuid4()),
        "title": "QuestBridge National College Match",
        "organization": "QuestBridge",
        "type": "scholarship",
        "field": "Multidisciplinary",
        "description": "Full four-year scholarships to top US colleges for high-achieving, low-income high school seniors.",
        "country": "USA",
        "remote": False,
        "grade_levels": ["high_school"],
        "eligibility": "U.S. seniors with strong academics from low-income backgrounds.",
        "deadline": _date(55),
        "prize": "Full-ride to partner colleges",
        "url": "https://www.scholarships.com",
        "source": "Scholarships.com",
        "tags": ["Scholarship", "Full-Ride", "Need-Based"],
        "featured": False,
        "popularity": 1670,
    },
    {
        "id": str(uuid.uuid4()),
        "title": "Stanford AI4ALL Summer Program",
        "organization": "Stanford University",
        "type": "research",
        "field": "Artificial Intelligence",
        "description": "Three-week residential program introducing high schoolers from underrepresented backgrounds to AI research.",
        "country": "USA",
        "remote": False,
        "grade_levels": ["high_school"],
        "eligibility": "9th graders (rising 10th) from underrepresented groups in AI.",
        "deadline": _date(48),
        "prize": "Tuition-free program",
        "url": "https://ai-4-all.org/",
        "source": "BigFuture",
        "tags": ["AI", "Research", "Diversity"],
        "featured": False,
        "popularity": 891,
    },
    {
        "id": str(uuid.uuid4()),
        "title": "TKS (The Knowledge Society)",
        "organization": "TKS Global",
        "type": "leadership",
        "field": "Innovation",
        "description": "Human accelerator for ambitious teenagers. Work on real-world problems with industry mentors over 10 months.",
        "country": "Global",
        "remote": True,
        "grade_levels": ["high_school"],
        "eligibility": "Ages 13–17. Selective, application-based.",
        "deadline": _date(15),
        "prize": "Industry connections + portfolio",
        "url": "https://www.tks.world/",
        "source": "BigFuture",
        "tags": ["Leadership", "Mentorship", "Teen"],
        "featured": False,
        "popularity": 743,
    },
    {
        "id": str(uuid.uuid4()),
        "title": "NASA SEES Internship",
        "organization": "NASA",
        "type": "internship",
        "field": "STEM",
        "description": "NASA STEM Enhancement in Earth Science — paid summer internship for U.S. high schoolers. Conduct real Earth science research.",
        "country": "USA",
        "remote": True,
        "grade_levels": ["high_school"],
        "eligibility": "U.S. citizens, 16+, 3.5 GPA, high school sophomores/juniors.",
        "deadline": _date(33),
        "prize": "Paid internship + research credit",
        "url": "https://www.csr.utexas.edu/education/sees/",
        "source": "BigFuture",
        "tags": ["NASA", "Internship", "Research"],
        "featured": True,
        "popularity": 1233,
    },
    {
        "id": str(uuid.uuid4()),
        "title": "Adobe Creativity Scholarship",
        "organization": "Adobe Foundation",
        "type": "scholarship",
        "field": "Design",
        "description": "$5,000 scholarship + Creative Cloud subscription for creative students pursuing arts, design, or media.",
        "country": "USA",
        "remote": True,
        "grade_levels": ["high_school", "undergrad"],
        "eligibility": "Creative portfolio + essay required.",
        "deadline": _date(25),
        "prize": "$5,000 + Adobe CC",
        "url": "https://www.scholarships.com",
        "source": "Scholarships.com",
        "tags": ["Design", "Creative", "Scholarship"],
        "featured": False,
        "popularity": 567,
    },
]


async def seed_if_empty(db) -> None:
    count = await db.opportunities.count_documents({})
    if count == 0:
        await db.opportunities.insert_many([{**o} for o in SEED_OPPORTUNITIES])
